steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'tpus', 'create', "$PROJECT_ID-tpu", '--network=default', '--range=10.240.1.0/29', '--version=1.9', '--zone=us-central1-f', '--preemptible']
- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'tpus', 'delete', "$PROJECT_ID-tpu", '--zone=us-central1-f']
