#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gpu-base-image', '-f', 'Dockerfile.gpu-base', '.']
#images: [ 'gcr.io/$PROJECT_ID/gpu-base-image' ]

# tpu cloud build 23
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/deepxor-gpu-image', '.' ]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'create'
  - '-f'
  - 'job-deepxor-gpu.yml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images: [ 'gcr.io/$PROJECT_ID/deepxor-gpu-image' ]
