#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tpu-base-image', '-f', 'Dockerfile.tpu-base', '.']
#images: [ 'gcr.io/$PROJECT_ID/tpu-base-image' ]

# tpu cloud build 19
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/deepxor-tpu-image', '.' ]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'create'
  - '-f'
  - 'job-deepxor-gpu.yml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images: [ 'gcr.io/$PROJECT_ID/deepxor-tpu-image' ]
